name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install sonar:sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          entryPoint: './gradlew'  # Adjust if you're using Maven, Ant, or other build tools
          args: 'sonarqube'
          projectBaseDir: '.'  # Adjust if your project directory is different
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
