name: SonarCloud Scan

on:
  push:
    branches:
      - main  # change this to your main branch name
      - develop  # you can add more branches as needed
  pull_request:
    branches:
      - main  # change this to your main branch name
      - develop  # you can add more branches as needed

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn -B clean package

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          organization: "your-organization-key"
          token: ${{ secrets.SONAR_TOKEN }}
          project-key: "your-project-key"
          # Additional properties can be added based on your SonarCloud configuration
